[package]
name = "wifix-mobile"
version = "0.1.0"
description = "WifiX mobile app for testing the shared React interface on Android."
authors = ["Mehmood Ul Haq"]
license = "MIT"
repository = "https://github.com/mehmoodulhaq570/WifiX"
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "wifix_mobile_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "=2.6.3", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "=2.11.5", features = [] }
tauri-plugin-log = "=2.8.0"
tokio = { version = "1.41", features = ["rt-multi-thread"] }
wifix-server = { path = "../../../../crates/wifix-server" }
